
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME:postgres}
quarkus.datasource.password=${DB_PASSWORD:portalmissionario123}
quarkus.hibernate-orm.dialect=org.hibernate.dialect.PostgreSQLDialect
quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://127.0.0.1:5434/portalmissionario}
quarkus.hibernate-orm.database.generation=update

quarkus.datasource.jdbc.max-size=10
quarkus.datasource.jdbc.min-size=2
quarkus.datasource.jdbc.query-timeout=300

quarkus.datasource.jdbc.idle-removal-interval=10
quarkus.datasource.jdbc.background-validation-interval=60

quarkus.hibernate-orm.query.plan-cache-max-size=512
quarkus.http.host=0.0.0.0

# Transação
quarkus.transaction-manager.timeout=300

# Habilita o log das consultas SQL geradas pelo Hibernate
quarkus.hibernate-orm.log.sql=true

# Habilita o log dos parâmetros das consultas SQL
quarkus.hibernate-orm.log.bind-parameters=true

# Configurações do servidor
quarkus.http.port=${PORT:8086}
quarkus.http.cors=true
quarkus.http.cors.origins=*
